# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_packages:
  - covr
  - testthat
after_success:
  - travis_wait 60 Rscript -e 'covr::codecov()'
